-- generated by lunar-bundler

local __modules = {}
local __require = require
local function require(name)
    if __modules[name] ~= nil then
        return __modules[name]
    end
    return __require(name)
end

local function __module_wrap(name, path, fn)
    local ok, result = xpcall(fn, function(err)
        local msg = "module '" .. name .. "' (" .. path .. "): " .. tostring(err)
        if debug and debug.traceback then
            msg = debug.traceback(msg, 2)
        end
        return msg
    end)
    if not ok then
        error(result, 0)
    end
    return result
end

-- /home/rgb/projects/lunar-bundler/demo/src/utils.lua
__modules["src.utils"] = __module_wrap("src.utils", "/home/rgb/projects/lunar-bundler/demo/src/utils.lua", function()
local M = {}

function M.log(msg)
    print("[lunar] " .. msg)
end

return M
end)

-- /home/rgb/projects/lunar-bundler/demo/src/greeter.lua
__modules["src.greeter"] = __module_wrap("src.greeter", "/home/rgb/projects/lunar-bundler/demo/src/greeter.lua", function()
local utils = require("src.utils")
local M = {}

function M.greet(name)
    utils.log("greeting: " .. name)
    print("hello, " .. name .. "!")
end

return M
end)

-- /home/rgb/projects/lunar-bundler/demo/src/config.lua
__modules["src.config"] = __module_wrap("src.config", "/home/rgb/projects/lunar-bundler/demo/src/config.lua", function()
local utils = require("src.utils")
local M = {}

local store = {
    name = "world",
    language = "lua",
}

function M.get(key)
    utils.log("fetching config key: " .. key)
    return store[key]
end

return M
end)

-- /home/rgb/projects/lunar-bundler/demo/main.lua
-- example app that requires from many sources

local greeter = require("src.greeter")
local config = require("src.config")

greeter.greet(config.get("name"))
greeter.greet(config.get("language"))
--# sourceMappingURL=bundle.lua.map
