-- generated by lunar-bundler

local __modules = {}
local __require = require
local function require(name)
    if __modules[name] ~= nil then
        return __modules[name]
    end
    return __require(name)
end

-- /home/rgb/projects/lunar-bundler/demo/src/utils.lua
__modules["src.utils"] = (function()
local M = {}

function M.log(msg)
    print("[lunar] " .. msg)
end

return M
end)()

-- /home/rgb/projects/lunar-bundler/demo/src/greeter.lua
__modules["src.greeter"] = (function()
local utils = require("src.utils")
local M = {}

function M.greet(name)
    utils.log("greeting: " .. name)
    print("hello, " .. name .. "!")
end

return M
end)()

-- /home/rgb/projects/lunar-bundler/demo/src/config.lua
__modules["src.config"] = (function()
local utils = require("src.utils")
local M = {}

local store = {
    name = "world",
    language = "lua",
}

function M.get(key)
    utils.log("fetching config key: " .. key)
    return store[key]
end

return M
end)()

-- /home/rgb/projects/lunar-bundler/demo/main.lua
-- example app that requires from many sources

local greeter = require("src.greeter")
local config = require("src.config")

greeter.greet(config.get("name"))
greeter.greet(config.get("language"))

