//! Emits the final bundle from a resolved dependency graph.
//!
//! Each dependency is wrapped in an IIFE assigned to `__modules["name"]`.
//! The entry point is inlined raw at the bottom. A small runtime shim
//! replaces `require()` to look up modules from `__modules` before
//! falling back to the real `require()` for unbundled modules.
use crate::graph::{DependencyGraph, Module};

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::{DependencyGraph, Module};
    use std::path::PathBuf;

    fn make_module(name: &str, source: &str) -> Module {
        Module {
            path: PathBuf::from(format!("{}.lua", name)),
            module_name: name.to_string(),
            source: source.to_string(),
        }
    }

    #[test]
    fn test_emit_basic() {
        let graph = DependencyGraph {
            modules: vec![
                make_module("foo", "return {}"),
                make_module("__entry__", r#"local x = require("foo")"#),
            ],
        };

        let emitter = Emitter::new(None, None);
        let out = emitter.emit(&graph);

        assert!(out.contains("__modules[\"foo\"]"));
        assert!(out.contains("return {}"));
        assert!(out.contains(r#"local x = require("foo")"#));
        // entry point should NOT be wrapped in __modules
        assert!(!out.contains("__modules[\"__entry__\"]"));
    }

    #[test]
    fn test_emit_inject_top() {
        let graph = DependencyGraph {
            modules: vec![make_module("__entry__", "print('hello')")],
        };

        let emitter = Emitter::new(Some("-- injected top".to_string()), None);
        let out = emitter.emit(&graph);

        // top injection should appear before the runtime shim
        let top_pos = out.find("-- injected top").unwrap();
        let shim_pos = out.find("local __modules").unwrap();
        assert!(top_pos < shim_pos);
    }

    #[test]
    fn test_emit_inject_bottom() {
        let graph = DependencyGraph {
            modules: vec![make_module("__entry__", "print('hello')")],
        };

        let emitter = Emitter::new(None, Some("-- injected bottom".to_string()));
        let out = emitter.emit(&graph);

        let entry_pos = out.find("print('hello')").unwrap();
        let bottom_pos = out.find("-- injected bottom").unwrap();
        assert!(entry_pos < bottom_pos);
    }

    #[test]
    fn test_require_fallback_in_shim() {
        let graph = DependencyGraph {
            modules: vec![make_module("__entry__", "")],
        };

        let emitter = Emitter::new(None, None);
        let out = emitter.emit(&graph);

        // shim should fall back to real require for unbundled modules
        assert!(out.contains("return __require(name)"));
    }
}

pub struct Emitter {
    pub inject_top: Option<String>,
    pub inject_bottom: Option<String>,
}

impl Emitter {
    pub fn new(inject_top: Option<String>, inject_bottom: Option<String>) -> Self {
        Self {
            inject_top,
            inject_bottom,
        }
    }

    pub fn emit(&self, graph: &DependencyGraph) -> String {
        let mut out = String::new();

        // header
        out.push_str("-- generated by lunar-bundler\n");

        // top injection
        if let Some(top) = &self.inject_top {
            out.push_str(top);
            out.push('\n');
        }

        // runtime shim
        out.push_str(
            r#"
local __modules = {}
local __require = require
local function require(name)
    if __modules[name] ~= nil then
        return __modules[name]
    end
    return __require(name)
end
"#,
        );

        // emit each dependency as a wrapped module, entry point last
        let (entry, deps) = graph.modules.split_last().unwrap();

        for module in deps {
            out.push_str(&self.emit_module(module));
        }

        // entry point inlined raw
        out.push_str(&format!("\n-- {}\n", entry.path.display()));
        out.push_str(&entry.source);
        out.push('\n');

        // bottom injection
        if let Some(bottom) = &self.inject_bottom {
            out.push_str(bottom);
            out.push('\n');
        }

        out
    }

    fn emit_module(&self, module: &Module) -> String {
        format!(
            "\n-- {path}\n__modules[\"{name}\"] = (function()\n{source}\nend)()\n",
            path = module.path.display(),
            name = module.module_name,
            source = module.source,
        )
    }
}
